.TH CD "1" "December 2014" "JKsh coreutils 0.1.0" "User Commands"
.SH NAME
cd \- Change the shell working directory
.SH SYNOPSIS
.B cd
[\fDIR\fR]
.SH DESCRIPTION
.PP    
Change the current directory to DIR.
.TP
\fB\-\-help\fR
display short help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by J. K. Kim.
.SH COPYRIGHT
Copyright \(co 2014 J. K. Kim <copy_x@naver.com>
.br
License GPLv2: GNU GPL version 2.