.TH LS "1" "December 2014" "JKsh coreutils 0.1.0" "User Commands"
.SH NAME
ls \- list directory contents
.SH SYNOPSIS
.B ls
[\fOPTION\fR]... [\fFILE\fR]...
.SH DESCRIPTION
.PP    
List  information  about  the  FILEs (the current directory by default).
.TP
\fB\-l\fR
use a long listing format
.TP
\fB\-\-help\fR
display short help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by J. K. Kim.
.SH COPYRIGHT
Copyright \(co 2014 J. K. Kim <copy_x@naver.com>
.br
License GPLv2: GNU GPL version 2.